# Custom Language File for Launcher Customizer

[ejs.app]
title = "마크 대운동회"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/chuichui07"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "https://ch.sooplive.co.kr/chuichui07"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/chuichui07"
supportLink = "https://github.com/mchlauncher/chuichui07/issues"

[ejs.welcome]
welcomeHeader = "마크 대운동회"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."